// Ability constants (sourced from include/constants/pokemon.h).
// Each entry maps the ABILITY_* enum to a human-readable label.
export interface AbilityOption {
  value: string;
  label: string;
}

export const ABILITY_OPTIONS: readonly AbilityOption[] = [
  { value: 'ABILITY_NONE', label: 'None' },
  { value: 'ABILITY_STENCH', label: 'Stench' },
  { value: 'ABILITY_DRIZZLE', label: 'Drizzle' },
  { value: 'ABILITY_SPEED_BOOST', label: 'Speed Boost' },
  { value: 'ABILITY_BATTLE_ARMOR', label: 'Battle Armor' },
  { value: 'ABILITY_STURDY', label: 'Sturdy' },
  { value: 'ABILITY_DAMP', label: 'Damp' },
  { value: 'ABILITY_LIMBER', label: 'Limber' },
  { value: 'ABILITY_SAND_VEIL', label: 'Sand Veil' },
  { value: 'ABILITY_STATIC', label: 'Static' },
  { value: 'ABILITY_VOLT_ABSORB', label: 'Volt Absorb' },
  { value: 'ABILITY_WATER_ABSORB', label: 'Water Absorb' },
  { value: 'ABILITY_OBLIVIOUS', label: 'Oblivious' },
  { value: 'ABILITY_CLOUD_NINE', label: 'Cloud Nine' },
  { value: 'ABILITY_COMPOUND_EYES', label: 'Compound Eyes' },
  { value: 'ABILITY_INSOMNIA', label: 'Insomnia' },
  { value: 'ABILITY_COLOR_CHANGE', label: 'Color Change' },
  { value: 'ABILITY_IMMUNITY', label: 'Immunity' },
  { value: 'ABILITY_FLASH_FIRE', label: 'Flash Fire' },
  { value: 'ABILITY_SHIELD_DUST', label: 'Shield Dust' },
  { value: 'ABILITY_OWN_TEMPO', label: 'Own Tempo' },
  { value: 'ABILITY_SUCTION_CUPS', label: 'Suction Cups' },
  { value: 'ABILITY_INTIMIDATE', label: 'Intimidate' },
  { value: 'ABILITY_LEVITATE', label: 'Levitate' },
  { value: 'ABILITY_CLEAR_BODY', label: 'Clear Body' },
  { value: 'ABILITY_NATURAL_CURE', label: 'Natural Cure' },
  { value: 'ABILITY_LIGHTNING_ROD', label: 'Lightning Rod' },
  { value: 'ABILITY_SERENE_GRACE', label: 'Serene Grace' },
  { value: 'ABILITY_SWIFT_SWIM', label: 'Swift Swim' },
  { value: 'ABILITY_CHLOROPHYLL', label: 'Chlorophyll' },
  { value: 'ABILITY_ILLUMINATE', label: 'Illuminate' },
  { value: 'ABILITY_TRACE', label: 'Trace' },
  { value: 'ABILITY_HUGE_POWER', label: 'Huge Power' },
  { value: 'ABILITY_POISON_POINT', label: 'Poison Point' },
  { value: 'ABILITY_INNER_FOCUS', label: 'Inner Focus' },
  { value: 'ABILITY_MAGMA_ARMOR', label: 'Magma Armor' },
  { value: 'ABILITY_WATER_VEIL', label: 'Water Veil' },
  { value: 'ABILITY_MAGNET_PULL', label: 'Magnet Pull' },
  { value: 'ABILITY_SOUNDPROOF', label: 'Soundproof' },
  { value: 'ABILITY_RAIN_DISH', label: 'Rain Dish' },
  { value: 'ABILITY_SAND_STREAM', label: 'Sand Stream' },
  { value: 'ABILITY_PRESSURE', label: 'Pressure' },
  { value: 'ABILITY_THICK_FAT', label: 'Thick Fat' },
  { value: 'ABILITY_EARLY_BIRD', label: 'Early Bird' },
  { value: 'ABILITY_FLAME_BODY', label: 'Flame Body' },
  { value: 'ABILITY_RUN_AWAY', label: 'Run Away' },
  { value: 'ABILITY_KEEN_EYE', label: 'Keen Eye' },
  { value: 'ABILITY_HYPER_CUTTER', label: 'Hyper Cutter' },
  { value: 'ABILITY_PICKUP', label: 'Pickup' },
  { value: 'ABILITY_TRUANT', label: 'Truant' },
  { value: 'ABILITY_HUSTLE', label: 'Hustle' },
  { value: 'ABILITY_HUGE_POWER_2', label: 'Huge Power (2)' },
  { value: 'ABILITY_POISON_HEAL', label: 'Poison Heal' },
  { value: 'ABILITY_OVERGROW', label: 'Overgrow' },
  { value: 'ABILITY_BLAZE', label: 'Blaze' },
  { value: 'ABILITY_TORRENT', label: 'Torrent' },
  { value: 'ABILITY_SHED_SKIN', label: 'Shed Skin' },
  { value: 'ABILITY_SWARM', label: 'Swarm' },
  { value: 'ABILITY_GUTS', label: 'Guts' },
  { value: 'ABILITY_CUTE_CHARM', label: 'Cute Charm' },
  { value: 'ABILITY_EFFECT_SPORE', label: 'Effect Spore' },
  { value: 'ABILITY_ARENA_TRAP', label: 'Arena Trap' },
  { value: 'ABILITY_VITAL_SPIRIT', label: 'Vital Spirit' },
  { value: 'ABILITY_SYNCHRONIZE', label: 'Synchronize' },
  { value: 'ABILITY_LIQUID_OOZE', label: 'Liquid Ooze' },
  { value: 'ABILITY_ROCK_HEAD', label: 'Rock Head' },
  { value: 'ABILITY_STICKY_HOLD', label: 'Sticky Hold' },
  { value: 'ABILITY_SHELL_ARMOR', label: 'Shell Armor' },
  { value: 'ABILITY_SHADOW_TAG', label: 'Shadow Tag' },
  { value: 'ABILITY_WONDER_GUARD', label: 'Wonder Guard' },
  { value: 'ABILITY_WHITE_SMOKE', label: 'White Smoke' },
  { value: 'ABILITY_ROUGH_SKIN', label: 'Rough Skin' },
  { value: 'ABILITY_PLUS', label: 'Plus' },
  { value: 'ABILITY_MINUS', label: 'Minus' },
  { value: 'ABILITY_PURE_POWER', label: 'Pure Power' },
  { value: 'ABILITY_FORECAST', label: 'Forecast' },
  { value: 'ABILITY_DROUGHT', label: 'Drought' },
  { value: 'ABILITY_AIR_LOCK', label: 'Air Lock' },
  { value: 'ABILITY_MARVEL_SCALE', label: 'Marvel Scale' },
];
