// Authoritative move names, sourced from src/data/text/move_names.h
// (the same table the game uses to display move names).
export const MOVE_NAME_MAP: Readonly<Record<string, string>> = {
  "MOVE_NONE": "-",
  "MOVE_POUND": "Pound",
  "MOVE_KARATE_CHOP": "Karate Chop",
  "MOVE_DOUBLE_SLAP": "Doubleslap",
  "MOVE_COMET_PUNCH": "Comet Punch",
  "MOVE_MEGA_PUNCH": "Mega Punch",
  "MOVE_PAY_DAY": "Pay Day",
  "MOVE_FIRE_PUNCH": "Fire Punch",
  "MOVE_ICE_PUNCH": "Ice Punch",
  "MOVE_THUNDER_PUNCH": "Thunderpunch",
  "MOVE_SCRATCH": "Scratch",
  "MOVE_VICE_GRIP": "Vicegrip",
  "MOVE_GUILLOTINE": "Guillotine",
  "MOVE_RAZOR_WIND": "Razor Wind",
  "MOVE_SWORDS_DANCE": "Swords Dance",
  "MOVE_CUT": "Cut",
  "MOVE_GUST": "Gust",
  "MOVE_WING_ATTACK": "Wing Attack",
  "MOVE_WHIRLWIND": "Whirlwind",
  "MOVE_FLY": "Fly",
  "MOVE_BIND": "Bind",
  "MOVE_SLAM": "Slam",
  "MOVE_VINE_WHIP": "Vine Whip",
  "MOVE_STOMP": "Stomp",
  "MOVE_DOUBLE_KICK": "Double Kick",
  "MOVE_MEGA_KICK": "Mega Kick",
  "MOVE_JUMP_KICK": "Jump Kick",
  "MOVE_ROLLING_KICK": "Rolling Kick",
  "MOVE_SAND_ATTACK": "Sand-attack",
  "MOVE_HEADBUTT": "Headbutt",
  "MOVE_HORN_ATTACK": "Horn Attack",
  "MOVE_FURY_ATTACK": "Fury Attack",
  "MOVE_HORN_DRILL": "Horn Drill",
  "MOVE_TACKLE": "Tackle",
  "MOVE_BODY_SLAM": "Body Slam",
  "MOVE_WRAP": "Wrap",
  "MOVE_TAKE_DOWN": "Take Down",
  "MOVE_THRASH": "Thrash",
  "MOVE_DOUBLE_EDGE": "Double-edge",
  "MOVE_TAIL_WHIP": "Tail Whip",
  "MOVE_POISON_STING": "Poison Sting",
  "MOVE_TWINEEDLE": "Twineedle",
  "MOVE_PIN_MISSILE": "Pin Missile",
  "MOVE_LEER": "Leer",
  "MOVE_BITE": "Bite",
  "MOVE_GROWL": "Growl",
  "MOVE_ROAR": "Roar",
  "MOVE_SING": "Sing",
  "MOVE_SUPERSONIC": "Supersonic",
  "MOVE_SONIC_BOOM": "Sonicboom",
  "MOVE_DISABLE": "Disable",
  "MOVE_ACID": "Acid",
  "MOVE_EMBER": "Ember",
  "MOVE_FLAMETHROWER": "Flamethrower",
  "MOVE_MIST": "Mist",
  "MOVE_WATER_GUN": "Water Gun",
  "MOVE_HYDRO_PUMP": "Hydro Pump",
  "MOVE_SURF": "Surf",
  "MOVE_ICE_BEAM": "Ice Beam",
  "MOVE_BLIZZARD": "Blizzard",
  "MOVE_PSYBEAM": "Psybeam",
  "MOVE_BUBBLE_BEAM": "Bubblebeam",
  "MOVE_AURORA_BEAM": "Aurora Beam",
  "MOVE_HYPER_BEAM": "Hyper Beam",
  "MOVE_PECK": "Peck",
  "MOVE_DRILL_PECK": "Drill Peck",
  "MOVE_SUBMISSION": "Submission",
  "MOVE_LOW_KICK": "Low Kick",
  "MOVE_COUNTER": "Counter",
  "MOVE_SEISMIC_TOSS": "Seismic Toss",
  "MOVE_STRENGTH": "Strength",
  "MOVE_ABSORB": "Absorb",
  "MOVE_MEGA_DRAIN": "Mega Drain",
  "MOVE_LEECH_SEED": "Leech Seed",
  "MOVE_GROWTH": "Growth",
  "MOVE_RAZOR_LEAF": "Razor Leaf",
  "MOVE_SOLAR_BEAM": "Solarbeam",
  "MOVE_POISON_POWDER": "Poisonpowder",
  "MOVE_STUN_SPORE": "Stun Spore",
  "MOVE_SLEEP_POWDER": "Sleep Powder",
  "MOVE_PETAL_DANCE": "Petal Dance",
  "MOVE_STRING_SHOT": "String Shot",
  "MOVE_DRAGON_RAGE": "Dragon Rage",
  "MOVE_FIRE_SPIN": "Fire Spin",
  "MOVE_THUNDER_SHOCK": "Thundershock",
  "MOVE_THUNDERBOLT": "Thunderbolt",
  "MOVE_THUNDER_WAVE": "Thunder Wave",
  "MOVE_THUNDER": "Thunder",
  "MOVE_ROCK_THROW": "Rock Throw",
  "MOVE_EARTHQUAKE": "Earthquake",
  "MOVE_FISSURE": "Fissure",
  "MOVE_DIG": "Dig",
  "MOVE_TOXIC": "Toxic",
  "MOVE_CONFUSION": "Confusion",
  "MOVE_PSYCHIC": "Psychic",
  "MOVE_HYPNOSIS": "Hypnosis",
  "MOVE_MEDITATE": "Meditate",
  "MOVE_AGILITY": "Agility",
  "MOVE_QUICK_ATTACK": "Quick Attack",
  "MOVE_RAGE": "Rage",
  "MOVE_TELEPORT": "Teleport",
  "MOVE_NIGHT_SHADE": "Night Shade",
  "MOVE_MIMIC": "Mimic",
  "MOVE_SCREECH": "Screech",
  "MOVE_DOUBLE_TEAM": "Double Team",
  "MOVE_RECOVER": "Recover",
  "MOVE_HARDEN": "Harden",
  "MOVE_MINIMIZE": "Minimize",
  "MOVE_SMOKESCREEN": "Smokescreen",
  "MOVE_CONFUSE_RAY": "Confuse Ray",
  "MOVE_WITHDRAW": "Withdraw",
  "MOVE_DEFENSE_CURL": "Defense Curl",
  "MOVE_BARRIER": "Barrier",
  "MOVE_LIGHT_SCREEN": "Light Screen",
  "MOVE_HAZE": "Haze",
  "MOVE_REFLECT": "Reflect",
  "MOVE_FOCUS_ENERGY": "Focus Energy",
  "MOVE_BIDE": "Bide",
  "MOVE_METRONOME": "Metronome",
  "MOVE_MIRROR_MOVE": "Mirror Move",
  "MOVE_SELF_DESTRUCT": "Selfdestruct",
  "MOVE_EGG_BOMB": "Egg Bomb",
  "MOVE_LICK": "Lick",
  "MOVE_SMOG": "Smog",
  "MOVE_SLUDGE": "Sludge",
  "MOVE_BONE_CLUB": "Bone Club",
  "MOVE_FIRE_BLAST": "Fire Blast",
  "MOVE_WATERFALL": "Waterfall",
  "MOVE_CLAMP": "Clamp",
  "MOVE_SWIFT": "Swift",
  "MOVE_SKULL_BASH": "Skull Bash",
  "MOVE_SPIKE_CANNON": "Spike Cannon",
  "MOVE_CONSTRICT": "Constrict",
  "MOVE_AMNESIA": "Amnesia",
  "MOVE_KINESIS": "Kinesis",
  "MOVE_SOFT_BOILED": "Softboiled",
  "MOVE_HI_JUMP_KICK": "Hi Jump Kick",
  "MOVE_GLARE": "Glare",
  "MOVE_DREAM_EATER": "Dream Eater",
  "MOVE_POISON_GAS": "Poison Gas",
  "MOVE_BARRAGE": "Barrage",
  "MOVE_LEECH_LIFE": "Leech Life",
  "MOVE_LOVELY_KISS": "Lovely Kiss",
  "MOVE_SKY_ATTACK": "Sky Attack",
  "MOVE_TRANSFORM": "Transform",
  "MOVE_BUBBLE": "Bubble",
  "MOVE_DIZZY_PUNCH": "Dizzy Punch",
  "MOVE_SPORE": "Spore",
  "MOVE_FLASH": "Flash",
  "MOVE_PSYWAVE": "Psywave",
  "MOVE_SPLASH": "Splash",
  "MOVE_ACID_ARMOR": "Acid Armor",
  "MOVE_CRABHAMMER": "Crabhammer",
  "MOVE_EXPLOSION": "Explosion",
  "MOVE_FURY_SWIPES": "Fury Swipes",
  "MOVE_BONEMERANG": "Bonemerang",
  "MOVE_REST": "Rest",
  "MOVE_ROCK_SLIDE": "Rock Slide",
  "MOVE_HYPER_FANG": "Hyper Fang",
  "MOVE_SHARPEN": "Sharpen",
  "MOVE_CONVERSION": "Conversion",
  "MOVE_TRI_ATTACK": "Tri Attack",
  "MOVE_SUPER_FANG": "Super Fang",
  "MOVE_SLASH": "Slash",
  "MOVE_SUBSTITUTE": "Substitute",
  "MOVE_STRUGGLE": "Struggle",
  "MOVE_SKETCH": "Sketch",
  "MOVE_TRIPLE_KICK": "Triple Kick",
  "MOVE_THIEF": "Thief",
  "MOVE_SPIDER_WEB": "Spider Web",
  "MOVE_MIND_READER": "Mind Reader",
  "MOVE_NIGHTMARE": "Nightmare",
  "MOVE_FLAME_WHEEL": "Flame Wheel",
  "MOVE_SNORE": "Snore",
  "MOVE_CURSE": "Curse",
  "MOVE_FLAIL": "Flail",
  "MOVE_CONVERSION_2": "Conversion 2",
  "MOVE_AEROBLAST": "Aeroblast",
  "MOVE_COTTON_SPORE": "Cotton Spore",
  "MOVE_REVERSAL": "Reversal",
  "MOVE_SPITE": "Spite",
  "MOVE_POWDER_SNOW": "Powder Snow",
  "MOVE_PROTECT": "Protect",
  "MOVE_MACH_PUNCH": "Mach Punch",
  "MOVE_SCARY_FACE": "Scary Face",
  "MOVE_FAINT_ATTACK": "Faint Attack",
  "MOVE_SWEET_KISS": "Sweet Kiss",
  "MOVE_BELLY_DRUM": "Belly Drum",
  "MOVE_SLUDGE_BOMB": "Sludge Bomb",
  "MOVE_MUD_SLAP": "Mud-slap",
  "MOVE_OCTAZOOKA": "Octazooka",
  "MOVE_SPIKES": "Spikes",
  "MOVE_ZAP_CANNON": "Zap Cannon",
  "MOVE_FORESIGHT": "Foresight",
  "MOVE_DESTINY_BOND": "Destiny Bond",
  "MOVE_PERISH_SONG": "Perish Song",
  "MOVE_ICY_WIND": "Icy Wind",
  "MOVE_DETECT": "Detect",
  "MOVE_BONE_RUSH": "Bone Rush",
  "MOVE_LOCK_ON": "Lock-on",
  "MOVE_OUTRAGE": "Outrage",
  "MOVE_SANDSTORM": "Sandstorm",
  "MOVE_GIGA_DRAIN": "Giga Drain",
  "MOVE_ENDURE": "Endure",
  "MOVE_CHARM": "Charm",
  "MOVE_ROLLOUT": "Rollout",
  "MOVE_FALSE_SWIPE": "False Swipe",
  "MOVE_SWAGGER": "Swagger",
  "MOVE_MILK_DRINK": "Milk Drink",
  "MOVE_SPARK": "Spark",
  "MOVE_FURY_CUTTER": "Fury Cutter",
  "MOVE_STEEL_WING": "Steel Wing",
  "MOVE_MEAN_LOOK": "Mean Look",
  "MOVE_ATTRACT": "Attract",
  "MOVE_SLEEP_TALK": "Sleep Talk",
  "MOVE_HEAL_BELL": "Heal Bell",
  "MOVE_RETURN": "Return",
  "MOVE_PRESENT": "Present",
  "MOVE_FRUSTRATION": "Frustration",
  "MOVE_SAFEGUARD": "Safeguard",
  "MOVE_PAIN_SPLIT": "Pain Split",
  "MOVE_SACRED_FIRE": "Sacred Fire",
  "MOVE_MAGNITUDE": "Magnitude",
  "MOVE_DYNAMIC_PUNCH": "Dynamicpunch",
  "MOVE_MEGAHORN": "Megahorn",
  "MOVE_DRAGON_BREATH": "Dragonbreath",
  "MOVE_BATON_PASS": "Baton Pass",
  "MOVE_ENCORE": "Encore",
  "MOVE_PURSUIT": "Pursuit",
  "MOVE_RAPID_SPIN": "Rapid Spin",
  "MOVE_SWEET_SCENT": "Sweet Scent",
  "MOVE_IRON_TAIL": "Iron Tail",
  "MOVE_METAL_CLAW": "Metal Claw",
  "MOVE_VITAL_THROW": "Vital Throw",
  "MOVE_MORNING_SUN": "Morning Sun",
  "MOVE_SYNTHESIS": "Synthesis",
  "MOVE_MOONLIGHT": "Moonlight",
  "MOVE_HIDDEN_POWER": "Hidden Power",
  "MOVE_CROSS_CHOP": "Cross Chop",
  "MOVE_TWISTER": "Twister",
  "MOVE_RAIN_DANCE": "Rain Dance",
  "MOVE_SUNNY_DAY": "Sunny Day",
  "MOVE_CRUNCH": "Crunch",
  "MOVE_MIRROR_COAT": "Mirror Coat",
  "MOVE_PSYCH_UP": "Psych Up",
  "MOVE_EXTREME_SPEED": "Extremespeed",
  "MOVE_ANCIENT_POWER": "Ancientpower",
  "MOVE_SHADOW_BALL": "Shadow Ball",
  "MOVE_FUTURE_SIGHT": "Future Sight",
  "MOVE_ROCK_SMASH": "Rock Smash",
  "MOVE_WHIRLPOOL": "Whirlpool",
  "MOVE_BEAT_UP": "Beat Up",
  "MOVE_FAKE_OUT": "Fake Out",
  "MOVE_UPROAR": "Uproar",
  "MOVE_STOCKPILE": "Stockpile",
  "MOVE_SPIT_UP": "Spit Up",
  "MOVE_SWALLOW": "Swallow",
  "MOVE_HEAT_WAVE": "Heat Wave",
  "MOVE_HAIL": "Hail",
  "MOVE_TORMENT": "Torment",
  "MOVE_FLATTER": "Flatter",
  "MOVE_WILL_O_WISP": "Will-o-wisp",
  "MOVE_MEMENTO": "Memento",
  "MOVE_FACADE": "Facade",
  "MOVE_FOCUS_PUNCH": "Focus Punch",
  "MOVE_SMELLING_SALT": "Smellingsalt",
  "MOVE_FOLLOW_ME": "Follow Me",
  "MOVE_NATURE_POWER": "Nature Power",
  "MOVE_CHARGE": "Charge",
  "MOVE_TAUNT": "Taunt",
  "MOVE_HELPING_HAND": "Helping Hand",
  "MOVE_TRICK": "Trick",
  "MOVE_ROLE_PLAY": "Role Play",
  "MOVE_WISH": "Wish",
  "MOVE_ASSIST": "Assist",
  "MOVE_INGRAIN": "Ingrain",
  "MOVE_SUPERPOWER": "Superpower",
  "MOVE_MAGIC_COAT": "Magic Coat",
  "MOVE_RECYCLE": "Recycle",
  "MOVE_REVENGE": "Revenge",
  "MOVE_BRICK_BREAK": "Brick Break",
  "MOVE_YAWN": "Yawn",
  "MOVE_KNOCK_OFF": "Knock Off",
  "MOVE_ENDEAVOR": "Endeavor",
  "MOVE_ERUPTION": "Eruption",
  "MOVE_SKILL_SWAP": "Skill Swap",
  "MOVE_IMPRISON": "Imprison",
  "MOVE_REFRESH": "Refresh",
  "MOVE_GRUDGE": "Grudge",
  "MOVE_SNATCH": "Snatch",
  "MOVE_SECRET_POWER": "Secret Power",
  "MOVE_DIVE": "Dive",
  "MOVE_ARM_THRUST": "Arm Thrust",
  "MOVE_CAMOUFLAGE": "Camouflage",
  "MOVE_TAIL_GLOW": "Tail Glow",
  "MOVE_LUSTER_PURGE": "Luster Purge",
  "MOVE_MIST_BALL": "Mist Ball",
  "MOVE_FEATHER_DANCE": "Featherdance",
  "MOVE_TEETER_DANCE": "Teeter Dance",
  "MOVE_BLAZE_KICK": "Blaze Kick",
  "MOVE_MUD_SPORT": "Mud Sport",
  "MOVE_ICE_BALL": "Ice Ball",
  "MOVE_NEEDLE_ARM": "Needle Arm",
  "MOVE_SLACK_OFF": "Slack Off",
  "MOVE_HYPER_VOICE": "Hyper Voice",
  "MOVE_POISON_FANG": "Poison Fang",
  "MOVE_CRUSH_CLAW": "Crush Claw",
  "MOVE_BLAST_BURN": "Blast Burn",
  "MOVE_HYDRO_CANNON": "Hydro Cannon",
  "MOVE_METEOR_MASH": "Meteor Mash",
  "MOVE_ASTONISH": "Astonish",
  "MOVE_WEATHER_BALL": "Weather Ball",
  "MOVE_AROMATHERAPY": "Aromatherapy",
  "MOVE_FAKE_TEARS": "Fake Tears",
  "MOVE_AIR_CUTTER": "Air Cutter",
  "MOVE_OVERHEAT": "Overheat",
  "MOVE_ODOR_SLEUTH": "Odor Sleuth",
  "MOVE_ROCK_TOMB": "Rock Tomb",
  "MOVE_SILVER_WIND": "Silver Wind",
  "MOVE_METAL_SOUND": "Metal Sound",
  "MOVE_GRASS_WHISTLE": "Grasswhistle",
  "MOVE_TICKLE": "Tickle",
  "MOVE_COSMIC_POWER": "Cosmic Power",
  "MOVE_WATER_SPOUT": "Water Spout",
  "MOVE_SIGNAL_BEAM": "Signal Beam",
  "MOVE_SHADOW_PUNCH": "Shadow Punch",
  "MOVE_EXTRASENSORY": "Extrasensory",
  "MOVE_SKY_UPPERCUT": "Sky Uppercut",
  "MOVE_SAND_TOMB": "Sand Tomb",
  "MOVE_SHEER_COLD": "Sheer Cold",
  "MOVE_MUDDY_WATER": "Muddy Water",
  "MOVE_BULLET_SEED": "Bullet Seed",
  "MOVE_AERIAL_ACE": "Aerial Ace",
  "MOVE_ICICLE_SPEAR": "Icicle Spear",
  "MOVE_IRON_DEFENSE": "Iron Defense",
  "MOVE_BLOCK": "Block",
  "MOVE_HOWL": "Howl",
  "MOVE_DRAGON_CLAW": "Dragon Claw",
  "MOVE_FRENZY_PLANT": "Frenzy Plant",
  "MOVE_BULK_UP": "Bulk Up",
  "MOVE_BOUNCE": "Bounce",
  "MOVE_MUD_SHOT": "Mud Shot",
  "MOVE_POISON_TAIL": "Poison Tail",
  "MOVE_COVET": "Covet",
  "MOVE_VOLT_TACKLE": "Volt Tackle",
  "MOVE_MAGICAL_LEAF": "Magical Leaf",
  "MOVE_WATER_SPORT": "Water Sport",
  "MOVE_CALM_MIND": "Calm Mind",
  "MOVE_LEAF_BLADE": "Leaf Blade",
  "MOVE_DRAGON_DANCE": "Dragon Dance",
  "MOVE_ROCK_BLAST": "Rock Blast",
  "MOVE_SHOCK_WAVE": "Shock Wave",
  "MOVE_WATER_PULSE": "Water Pulse",
  "MOVE_DOOM_DESIRE": "Doom Desire",
  "MOVE_PSYCHO_BOOST": "Psycho Boost"
};

// Ordered list of move constants for the level-up dropdown (enum order, excludes MOVE_NONE/UNAVAILABLE)
export const MOVE_LIST: readonly string[] = [
  "MOVE_ABSORB",
  "MOVE_ACID",
  "MOVE_ACID_ARMOR",
  "MOVE_AERIAL_ACE",
  "MOVE_AEROBLAST",
  "MOVE_AGILITY",
  "MOVE_AIR_CUTTER",
  "MOVE_AMNESIA",
  "MOVE_ANCIENT_POWER",
  "MOVE_ARM_THRUST",
  "MOVE_AROMATHERAPY",
  "MOVE_ASSIST",
  "MOVE_ASTONISH",
  "MOVE_ATTRACT",
  "MOVE_AURORA_BEAM",
  "MOVE_BARRAGE",
  "MOVE_BARRIER",
  "MOVE_BATON_PASS",
  "MOVE_BEAT_UP",
  "MOVE_BELLY_DRUM",
  "MOVE_BIDE",
  "MOVE_BIND",
  "MOVE_BITE",
  "MOVE_BLAST_BURN",
  "MOVE_BLAZE_KICK",
  "MOVE_BLIZZARD",
  "MOVE_BLOCK",
  "MOVE_BODY_SLAM",
  "MOVE_BONE_CLUB",
  "MOVE_BONE_RUSH",
  "MOVE_BONEMERANG",
  "MOVE_BOUNCE",
  "MOVE_BRICK_BREAK",
  "MOVE_BUBBLE",
  "MOVE_BUBBLE_BEAM",
  "MOVE_BULK_UP",
  "MOVE_BULLET_SEED",
  "MOVE_CALM_MIND",
  "MOVE_CAMOUFLAGE",
  "MOVE_CHARGE",
  "MOVE_CHARM",
  "MOVE_CLAMP",
  "MOVE_COMET_PUNCH",
  "MOVE_CONFUSE_RAY",
  "MOVE_CONFUSION",
  "MOVE_CONSTRICT",
  "MOVE_CONVERSION",
  "MOVE_CONVERSION_2",
  "MOVE_COSMIC_POWER",
  "MOVE_COTTON_SPORE",
  "MOVE_COUNTER",
  "MOVE_COVET",
  "MOVE_CRABHAMMER",
  "MOVE_CROSS_CHOP",
  "MOVE_CRUNCH",
  "MOVE_CRUSH_CLAW",
  "MOVE_CURSE",
  "MOVE_CUT",
  "MOVE_DEFENSE_CURL",
  "MOVE_DESTINY_BOND",
  "MOVE_DETECT",
  "MOVE_DIG",
  "MOVE_DISABLE",
  "MOVE_DIVE",
  "MOVE_DIZZY_PUNCH",
  "MOVE_DOOM_DESIRE",
  "MOVE_DOUBLE_KICK",
  "MOVE_DOUBLE_TEAM",
  "MOVE_DOUBLE_EDGE",
  "MOVE_DOUBLE_SLAP",
  "MOVE_DRAGON_CLAW",
  "MOVE_DRAGON_DANCE",
  "MOVE_DRAGON_RAGE",
  "MOVE_DRAGON_BREATH",
  "MOVE_DREAM_EATER",
  "MOVE_DRILL_PECK",
  "MOVE_DYNAMIC_PUNCH",
  "MOVE_EARTHQUAKE",
  "MOVE_EGG_BOMB",
  "MOVE_EMBER",
  "MOVE_ENCORE",
  "MOVE_ENDEAVOR",
  "MOVE_ENDURE",
  "MOVE_ERUPTION",
  "MOVE_EXPLOSION",
  "MOVE_EXTRASENSORY",
  "MOVE_EXTREME_SPEED",
  "MOVE_FACADE",
  "MOVE_FAINT_ATTACK",
  "MOVE_FAKE_OUT",
  "MOVE_FAKE_TEARS",
  "MOVE_FALSE_SWIPE",
  "MOVE_FEATHER_DANCE",
  "MOVE_FIRE_BLAST",
  "MOVE_FIRE_PUNCH",
  "MOVE_FIRE_SPIN",
  "MOVE_FISSURE",
  "MOVE_FLAIL",
  "MOVE_FLAME_WHEEL",
  "MOVE_FLAMETHROWER",
  "MOVE_FLASH",
  "MOVE_FLATTER",
  "MOVE_FLY",
  "MOVE_FOCUS_ENERGY",
  "MOVE_FOCUS_PUNCH",
  "MOVE_FOLLOW_ME",
  "MOVE_FORESIGHT",
  "MOVE_FRENZY_PLANT",
  "MOVE_FRUSTRATION",
  "MOVE_FURY_ATTACK",
  "MOVE_FURY_CUTTER",
  "MOVE_FURY_SWIPES",
  "MOVE_FUTURE_SIGHT",
  "MOVE_GIGA_DRAIN",
  "MOVE_GLARE",
  "MOVE_GRASS_WHISTLE",
  "MOVE_GROWL",
  "MOVE_GROWTH",
  "MOVE_GRUDGE",
  "MOVE_GUILLOTINE",
  "MOVE_GUST",
  "MOVE_HAIL",
  "MOVE_HARDEN",
  "MOVE_HAZE",
  "MOVE_HEADBUTT",
  "MOVE_HEAL_BELL",
  "MOVE_HEAT_WAVE",
  "MOVE_HELPING_HAND",
  "MOVE_HI_JUMP_KICK",
  "MOVE_HIDDEN_POWER",
  "MOVE_HORN_ATTACK",
  "MOVE_HORN_DRILL",
  "MOVE_HOWL",
  "MOVE_HYDRO_CANNON",
  "MOVE_HYDRO_PUMP",
  "MOVE_HYPER_BEAM",
  "MOVE_HYPER_FANG",
  "MOVE_HYPER_VOICE",
  "MOVE_HYPNOSIS",
  "MOVE_ICE_BALL",
  "MOVE_ICE_BEAM",
  "MOVE_ICE_PUNCH",
  "MOVE_ICICLE_SPEAR",
  "MOVE_ICY_WIND",
  "MOVE_IMPRISON",
  "MOVE_INGRAIN",
  "MOVE_IRON_DEFENSE",
  "MOVE_IRON_TAIL",
  "MOVE_JUMP_KICK",
  "MOVE_KARATE_CHOP",
  "MOVE_KINESIS",
  "MOVE_KNOCK_OFF",
  "MOVE_LEAF_BLADE",
  "MOVE_LEECH_LIFE",
  "MOVE_LEECH_SEED",
  "MOVE_LEER",
  "MOVE_LICK",
  "MOVE_LIGHT_SCREEN",
  "MOVE_LOCK_ON",
  "MOVE_LOVELY_KISS",
  "MOVE_LOW_KICK",
  "MOVE_LUSTER_PURGE",
  "MOVE_MACH_PUNCH",
  "MOVE_MAGIC_COAT",
  "MOVE_MAGICAL_LEAF",
  "MOVE_MAGNITUDE",
  "MOVE_MEAN_LOOK",
  "MOVE_MEDITATE",
  "MOVE_MEGA_DRAIN",
  "MOVE_MEGA_KICK",
  "MOVE_MEGA_PUNCH",
  "MOVE_MEGAHORN",
  "MOVE_MEMENTO",
  "MOVE_METAL_CLAW",
  "MOVE_METAL_SOUND",
  "MOVE_METEOR_MASH",
  "MOVE_METRONOME",
  "MOVE_MILK_DRINK",
  "MOVE_MIMIC",
  "MOVE_MIND_READER",
  "MOVE_MINIMIZE",
  "MOVE_MIRROR_COAT",
  "MOVE_MIRROR_MOVE",
  "MOVE_MIST",
  "MOVE_MIST_BALL",
  "MOVE_MOONLIGHT",
  "MOVE_MORNING_SUN",
  "MOVE_MUD_SHOT",
  "MOVE_MUD_SPORT",
  "MOVE_MUD_SLAP",
  "MOVE_MUDDY_WATER",
  "MOVE_NATURE_POWER",
  "MOVE_NEEDLE_ARM",
  "MOVE_NIGHT_SHADE",
  "MOVE_NIGHTMARE",
  "MOVE_OCTAZOOKA",
  "MOVE_ODOR_SLEUTH",
  "MOVE_OUTRAGE",
  "MOVE_OVERHEAT",
  "MOVE_PAIN_SPLIT",
  "MOVE_PAY_DAY",
  "MOVE_PECK",
  "MOVE_PERISH_SONG",
  "MOVE_PETAL_DANCE",
  "MOVE_PIN_MISSILE",
  "MOVE_POISON_FANG",
  "MOVE_POISON_GAS",
  "MOVE_POISON_STING",
  "MOVE_POISON_TAIL",
  "MOVE_POISON_POWDER",
  "MOVE_POUND",
  "MOVE_POWDER_SNOW",
  "MOVE_PRESENT",
  "MOVE_PROTECT",
  "MOVE_PSYBEAM",
  "MOVE_PSYCH_UP",
  "MOVE_PSYCHIC",
  "MOVE_PSYCHO_BOOST",
  "MOVE_PSYWAVE",
  "MOVE_PURSUIT",
  "MOVE_QUICK_ATTACK",
  "MOVE_RAGE",
  "MOVE_RAIN_DANCE",
  "MOVE_RAPID_SPIN",
  "MOVE_RAZOR_LEAF",
  "MOVE_RAZOR_WIND",
  "MOVE_RECOVER",
  "MOVE_RECYCLE",
  "MOVE_REFLECT",
  "MOVE_REFRESH",
  "MOVE_REST",
  "MOVE_RETURN",
  "MOVE_REVENGE",
  "MOVE_REVERSAL",
  "MOVE_ROAR",
  "MOVE_ROCK_BLAST",
  "MOVE_ROCK_SLIDE",
  "MOVE_ROCK_SMASH",
  "MOVE_ROCK_THROW",
  "MOVE_ROCK_TOMB",
  "MOVE_ROLE_PLAY",
  "MOVE_ROLLING_KICK",
  "MOVE_ROLLOUT",
  "MOVE_SACRED_FIRE",
  "MOVE_SAFEGUARD",
  "MOVE_SAND_TOMB",
  "MOVE_SAND_ATTACK",
  "MOVE_SANDSTORM",
  "MOVE_SCARY_FACE",
  "MOVE_SCRATCH",
  "MOVE_SCREECH",
  "MOVE_SECRET_POWER",
  "MOVE_SEISMIC_TOSS",
  "MOVE_SELF_DESTRUCT",
  "MOVE_SHADOW_BALL",
  "MOVE_SHADOW_PUNCH",
  "MOVE_SHARPEN",
  "MOVE_SHEER_COLD",
  "MOVE_SHOCK_WAVE",
  "MOVE_SIGNAL_BEAM",
  "MOVE_SILVER_WIND",
  "MOVE_SING",
  "MOVE_SKETCH",
  "MOVE_SKILL_SWAP",
  "MOVE_SKULL_BASH",
  "MOVE_SKY_ATTACK",
  "MOVE_SKY_UPPERCUT",
  "MOVE_SLACK_OFF",
  "MOVE_SLAM",
  "MOVE_SLASH",
  "MOVE_SLEEP_POWDER",
  "MOVE_SLEEP_TALK",
  "MOVE_SLUDGE",
  "MOVE_SLUDGE_BOMB",
  "MOVE_SMELLING_SALT",
  "MOVE_SMOG",
  "MOVE_SMOKESCREEN",
  "MOVE_SNATCH",
  "MOVE_SNORE",
  "MOVE_SOFT_BOILED",
  "MOVE_SOLAR_BEAM",
  "MOVE_SONIC_BOOM",
  "MOVE_SPARK",
  "MOVE_SPIDER_WEB",
  "MOVE_SPIKE_CANNON",
  "MOVE_SPIKES",
  "MOVE_SPIT_UP",
  "MOVE_SPITE",
  "MOVE_SPLASH",
  "MOVE_SPORE",
  "MOVE_STEEL_WING",
  "MOVE_STOCKPILE",
  "MOVE_STOMP",
  "MOVE_STRENGTH",
  "MOVE_STRING_SHOT",
  "MOVE_STRUGGLE",
  "MOVE_STUN_SPORE",
  "MOVE_SUBMISSION",
  "MOVE_SUBSTITUTE",
  "MOVE_SUNNY_DAY",
  "MOVE_SUPER_FANG",
  "MOVE_SUPERPOWER",
  "MOVE_SUPERSONIC",
  "MOVE_SURF",
  "MOVE_SWAGGER",
  "MOVE_SWALLOW",
  "MOVE_SWEET_KISS",
  "MOVE_SWEET_SCENT",
  "MOVE_SWIFT",
  "MOVE_SWORDS_DANCE",
  "MOVE_SYNTHESIS",
  "MOVE_TACKLE",
  "MOVE_TAIL_GLOW",
  "MOVE_TAIL_WHIP",
  "MOVE_TAKE_DOWN",
  "MOVE_TAUNT",
  "MOVE_TEETER_DANCE",
  "MOVE_TELEPORT",
  "MOVE_THIEF",
  "MOVE_THRASH",
  "MOVE_THUNDER",
  "MOVE_THUNDER_WAVE",
  "MOVE_THUNDERBOLT",
  "MOVE_THUNDER_PUNCH",
  "MOVE_THUNDER_SHOCK",
  "MOVE_TICKLE",
  "MOVE_TORMENT",
  "MOVE_TOXIC",
  "MOVE_TRANSFORM",
  "MOVE_TRI_ATTACK",
  "MOVE_TRICK",
  "MOVE_TRIPLE_KICK",
  "MOVE_TWINEEDLE",
  "MOVE_TWISTER",
  "MOVE_UPROAR",
  "MOVE_VICE_GRIP",
  "MOVE_VINE_WHIP",
  "MOVE_VITAL_THROW",
  "MOVE_VOLT_TACKLE",
  "MOVE_WATER_GUN",
  "MOVE_WATER_PULSE",
  "MOVE_WATER_SPORT",
  "MOVE_WATER_SPOUT",
  "MOVE_WATERFALL",
  "MOVE_WEATHER_BALL",
  "MOVE_WHIRLPOOL",
  "MOVE_WHIRLWIND",
  "MOVE_WILL_O_WISP",
  "MOVE_WING_ATTACK",
  "MOVE_WISH",
  "MOVE_WITHDRAW",
  "MOVE_WRAP",
  "MOVE_YAWN",
  "MOVE_ZAP_CANNON",
];

export const TM_LIST: readonly string[] = [
  "FOCUS_PUNCH",
  "DRAGON_CLAW",
  "WATER_PULSE",
  "CALM_MIND",
  "ROAR",
  "TOXIC",
  "HAIL",
  "BULK_UP",
  "BULLET_SEED",
  "HIDDEN_POWER",
  "SUNNY_DAY",
  "TAUNT",
  "ICE_BEAM",
  "BLIZZARD",
  "HYPER_BEAM",
  "LIGHT_SCREEN",
  "PROTECT",
  "RAIN_DANCE",
  "GIGA_DRAIN",
  "SAFEGUARD",
  "FRUSTRATION",
  "SOLAR_BEAM",
  "IRON_TAIL",
  "THUNDERBOLT",
  "THUNDER",
  "EARTHQUAKE",
  "RETURN",
  "DIG",
  "PSYCHIC",
  "SHADOW_BALL",
  "BRICK_BREAK",
  "DOUBLE_TEAM",
  "REFLECT",
  "SHOCK_WAVE",
  "FLAMETHROWER",
  "SLUDGE_BOMB",
  "SANDSTORM",
  "FIRE_BLAST",
  "ROCK_TOMB",
  "AERIAL_ACE",
  "TORMENT",
  "FACADE",
  "SECRET_POWER",
  "REST",
  "ATTRACT",
  "THIEF",
  "STEEL_WING",
  "SKILL_SWAP",
  "SNATCH",
  "OVERHEAT"
];

export const HM_LIST: readonly string[] = [
  "CUT",
  "FLY",
  "SURF",
  "STRENGTH",
  "FLASH",
  "ROCK_SMASH",
  "WATERFALL",
  "DIVE"
];
